name: Sync Leetcode

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"  # This sets the workflow to run every day at 1:00 AM UTC (7:30 AM IST)

permissions:
  contents: write  # Ensure the action has permission to commit changes

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Sync LeetCode Solutions
        id: sync
        uses: joshcai/leetcode-sync@v1.5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          leetcode-csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          destination-folder: .  # Replace with your folder name
          filter-duplicate-secs: "true"  # Set to true to avoid processing duplicates

      # Create Question Metadata
      - name: Create Question Metadata
        run: |
          cd leetcode-solutions  # Change to your destination folder
          for file in *.cpp; do
            # Check if the file is a .cpp file
            if [[ -f "$file" ]]; then
              # Extract the question title from the file name
              question_title="$(basename "$file" .cpp)"  # Extract title from .cpp filename
              question_slug="${question_title// /-}"  # Convert spaces to hyphens for the slug
              question_url="https://leetcode.com/problems/$question_slug/"  # Construct the question URL

              # Create or overwrite README.md in the question folder
              mkdir -p "$question_title"  # Create a directory for the question if it doesn't exist
              echo "# $question_title" > "${question_title}/README.md"
              echo "## Question URL" >> "${question_title}/README.md"
              echo "[Link to LeetCode Question]($question_url)" >> "${question_title}/README.md"
              echo "## Answer" >> "${question_title}/README.md"

              # Append the answer code to README
              echo "```cpp" >> "${question_title}/README.md"
              cat "$file" >> "${question_title}/README.md"  # Append the answer code to README
              echo "```" >> "${question_title}/README.md"
              echo "Created README.md for $question_title with URL."
            fi
          done

      # Clean up unwanted file types
      - name: Clean Up Submissions
        run: |
          cd leetcode-solutions
          # Remove any unwanted file types (PostgreSQL and SQL)
          find . -type f \( -name "*.sql" -o -name "*.pg" \) -exec rm -f {} \;
